-- ============================================================================
-- 雪峰滑雪租赁 数据库结构迁移（13 张业务表）
-- 来源：docs/02-数据设计.md + app/src/data/types.ts
--
-- 说明：
--   * 主键 bigint GENERATED BY DEFAULT AS IDENTITY（允许显式插入种子主键，
--     种子插入后需 setval 同步序列，见 seed_demo_data.sql 末尾）。
--   * 事件时间统一 timestamp（无时区），但写入时一律通过
--     timezone('Asia/Shanghai', clock_timestamp()) 生成上海本地时间，不依赖
--     数据库会话默认时区（见 create_rls_policies.sql 中的业务 RPC）。
--     纯日期用 date；金额 numeric(10,2)；状态 varchar + CHECK 枚举。
--   * 本文件不含任何密钥/凭据。accounts 不含任何密码字段，真实认证由
--     CloudBase Auth 负责（account.uid 关联）。本地 localStorage 模拟所用的
--     密码占位字段为纯前端字段，不迁移到云端。
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. skill_levels 技能等级
-- ---------------------------------------------------------------------------
CREATE TABLE skill_levels (
  skill_level_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level_name     varchar(20) NOT NULL UNIQUE CHECK (btrim(level_name) <> ''),
  sort_order     integer NOT NULL
);

-- ---------------------------------------------------------------------------
-- 2. stores 门店
-- ---------------------------------------------------------------------------
CREATE TABLE stores (
  store_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_name  varchar(50) NOT NULL CHECK (btrim(store_name) <> ''),
  address     varchar(200),
  phone       varchar(20)
);

-- ---------------------------------------------------------------------------
-- 3. customers 客户
--    姓名/地址/电话为 DataService 必填字段 → NOT NULL + 非空白；
--    email 可空，唯一性按 trim 后、大小写不敏感（见下方表达式唯一索引）。
-- ---------------------------------------------------------------------------
CREATE TABLE customers (
  customer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name   varchar(50) NOT NULL CHECK (btrim(full_name) <> ''),
  address     varchar(200) NOT NULL CHECK (btrim(address) <> ''),
  phone       varchar(20) NOT NULL CHECK (btrim(phone) <> ''),
  email       varchar(100),
  birth_year  integer CHECK (birth_year IS NULL OR (birth_year >= 1900 AND birth_year <= 2100)),
  height_cm   numeric(5,1) CHECK (height_cm IS NULL OR (height_cm >= 30 AND height_cm <= 260)),
  weight_kg   numeric(5,1) CHECK (weight_kg IS NULL OR (weight_kg >= 5 AND weight_kg <= 300)),
  shoe_size   numeric(3,1) CHECK (shoe_size IS NULL OR (shoe_size >= 15 AND shoe_size <= 55))
);

-- ---------------------------------------------------------------------------
-- 4. employees 员工（full_name 为 DataService 必填字段 → 非空白）
-- ---------------------------------------------------------------------------
CREATE TABLE employees (
  employee_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name   varchar(50) NOT NULL CHECK (btrim(full_name) <> ''),
  address     varchar(200),
  phone       varchar(20),
  email       varchar(100),
  notes       varchar(500)
);

-- ---------------------------------------------------------------------------
-- 5. contractors 承包商（name 为 DataService 必填字段 → 非空白）
-- ---------------------------------------------------------------------------
CREATE TABLE contractors (
  contractor_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          varchar(80) NOT NULL CHECK (btrim(name) <> ''),
  address       varchar(200),
  phone         varchar(20),
  email         varchar(100)
);

-- ---------------------------------------------------------------------------
-- 6. contractor_rates 承包商费率历史
--    UNIQUE(contractor_id, effective_date) 保证同承包商同日仅一条；
--    UNIQUE(contractor_id, rate_id) 作为 repair_orders 复合外键的引用目标。
-- ---------------------------------------------------------------------------
CREATE TABLE contractor_rates (
  rate_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contractor_id  bigint NOT NULL REFERENCES contractors(contractor_id),
  effective_date date NOT NULL,
  hourly_rate    numeric(10,2) NOT NULL CHECK (hourly_rate > 0),
  UNIQUE (contractor_id, effective_date),
  UNIQUE (contractor_id, rate_id)
);

-- ---------------------------------------------------------------------------
-- 7. rental_items 租赁物品（单品粒度；home_store_id 归属 / current_store_id 当前所在）
-- ---------------------------------------------------------------------------
CREATE TABLE rental_items (
  item_id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_code        varchar(20) NOT NULL UNIQUE CHECK (btrim(item_code) <> ''),
  name             varchar(80) NOT NULL CHECK (btrim(name) <> ''),
  description      varchar(200),
  category         varchar(20) NOT NULL CHECK (category IN ('滑雪板','雪靴','雪杖','单板','护目镜','头盔')),
  purchase_date    date,
  purchase_cost    numeric(10,2) CHECK (purchase_cost IS NULL OR purchase_cost >= 0),
  retail_price     numeric(10,2) CHECK (retail_price IS NULL OR retail_price >= 0),
  daily_rate       numeric(10,2) NOT NULL CHECK (daily_rate >= 0),
  skill_level_id   bigint REFERENCES skill_levels(skill_level_id),
  home_store_id    bigint NOT NULL REFERENCES stores(store_id),
  current_store_id bigint NOT NULL REFERENCES stores(store_id),
  status           varchar(20) NOT NULL DEFAULT '在库' CHECK (status IN ('在库','借出中','维修中','已报废')),
  -- 配件（护目镜/头盔）不设技能等级
  CHECK ((category IN ('护目镜','头盔') AND skill_level_id IS NULL)
         OR category NOT IN ('护目镜','头盔'))
);

-- ---------------------------------------------------------------------------
-- 8. rental_contracts 租赁合同（completed_at 与 status='已完成' 一一对应）
-- ---------------------------------------------------------------------------
CREATE TABLE rental_contracts (
  contract_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contract_no    varchar(20) NOT NULL UNIQUE,
  customer_id    bigint NOT NULL REFERENCES customers(customer_id),
  employee_id    bigint NOT NULL REFERENCES employees(employee_id),
  contract_date  date NOT NULL,
  duration_days  integer NOT NULL CHECK (duration_days > 0),
  total_amount   numeric(10,2) NOT NULL CHECK (total_amount >= 0),
  completed_at   timestamp,
  status         varchar(20) NOT NULL CHECK (status IN ('进行中','已完成')),
  CHECK ((status = '已完成') = (completed_at IS NOT NULL))
);

-- ---------------------------------------------------------------------------
-- 9. contract_lines 合同明细（单品粒度 quantity 恒为 1；UNIQUE(contract_id, item_id)）
--    状态与归还字段一致：借出中 → return 字段均空；已归还/已更换 → 均非空。
-- ---------------------------------------------------------------------------
CREATE TABLE contract_lines (
  contract_line_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contract_id       bigint NOT NULL REFERENCES rental_contracts(contract_id),
  item_id           bigint NOT NULL REFERENCES rental_items(item_id),
  quantity          integer NOT NULL DEFAULT 1 CHECK (quantity = 1),
  daily_rate        numeric(10,2) NOT NULL CHECK (daily_rate >= 0),
  checkout_time     timestamp NOT NULL,
  checkout_store_id bigint NOT NULL REFERENCES stores(store_id),
  return_time       timestamp,
  return_store_id   bigint REFERENCES stores(store_id),
  status            varchar(20) NOT NULL CHECK (status IN ('借出中','已归还','已更换')),
  UNIQUE (contract_id, item_id),
  CHECK (return_time IS NULL OR return_time > checkout_time),
  CHECK ((status = '借出中' AND return_time IS NULL AND return_store_id IS NULL)
         OR (status IN ('已归还','已更换') AND return_time IS NOT NULL AND return_store_id IS NOT NULL))
);

-- ---------------------------------------------------------------------------
-- 10. contract_changes 合同变更记录（换货拆两条共享 change_group_id）
--     change_id 由 identity 自动生成（不得显式写入后不推进序列）。
-- ---------------------------------------------------------------------------
CREATE TABLE contract_changes (
  change_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contract_id     bigint NOT NULL REFERENCES rental_contracts(contract_id),
  change_group_id bigint,
  change_date     timestamp NOT NULL,
  change_type     varchar(20) NOT NULL CHECK (change_type IN ('增加','归还')),
  item_id         bigint REFERENCES rental_items(item_id),
  quantity        integer NOT NULL DEFAULT 1 CHECK (quantity = 1),
  amount_delta    numeric(10,2),
  note            varchar(500)
);

-- ---------------------------------------------------------------------------
-- 11. repair_orders 维修单（rate_id 创建时按 request_date 冻结费率）
--     复合外键 (contractor_id, rate_id) → contractor_rates 保证费率归属同承包商。
-- ---------------------------------------------------------------------------
CREATE TABLE repair_orders (
  repair_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id          bigint NOT NULL REFERENCES rental_items(item_id),
  contractor_id    bigint NOT NULL REFERENCES contractors(contractor_id),
  rate_id          bigint NOT NULL,
  request_date     date NOT NULL,
  fault_description varchar(500) NOT NULL CHECK (btrim(fault_description) <> ''),
  repair_date      date,
  repair_hours     numeric(4,2),
  calculated_cost  numeric(10,2) CHECK (calculated_cost IS NULL OR calculated_cost >= 0),
  notes            varchar(500),
  status           varchar(20) NOT NULL CHECK (status IN ('待维修','维修中','已完成')),
  FOREIGN KEY (contractor_id, rate_id) REFERENCES contractor_rates(contractor_id, rate_id),
  CHECK (repair_date IS NULL OR repair_date >= request_date),
  CHECK (repair_hours IS NULL OR (repair_hours > 0 AND repair_hours % 0.25 = 0)),
  CHECK ((status = '已完成') = (repair_date IS NOT NULL AND repair_hours IS NOT NULL AND calculated_cost IS NOT NULL))
);

-- ---------------------------------------------------------------------------
-- 12. shifts 员工排班（UNIQUE(employee_id, work_date)；08:00–22:00）
-- ---------------------------------------------------------------------------
CREATE TABLE shifts (
  shift_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id bigint NOT NULL REFERENCES employees(employee_id),
  store_id    bigint NOT NULL REFERENCES stores(store_id),
  work_date   date NOT NULL,
  start_time  time NOT NULL,
  end_time    time NOT NULL,
  UNIQUE (employee_id, work_date),
  CHECK (start_time < end_time),
  CHECK (start_time >= TIME '08:00' AND end_time <= TIME '22:00')
);

-- ---------------------------------------------------------------------------
-- 13. accounts 账号（uid 关联 CloudBase Auth）
--     角色与关联实体精确映射：admin/staff → 关联员工；contractor → 关联承包商。
--     不含任何密码字段；密码由 CloudBase Auth 管理。
-- ---------------------------------------------------------------------------
CREATE TABLE accounts (
  account_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid           varchar(64) UNIQUE,
  username      varchar(50) NOT NULL UNIQUE CHECK (btrim(username) <> ''),
  role          varchar(20) NOT NULL CHECK (role IN ('admin','staff','contractor')),
  employee_id   bigint REFERENCES employees(employee_id),
  contractor_id bigint REFERENCES contractors(contractor_id),
  enabled       boolean NOT NULL DEFAULT true,
  CHECK ((role IN ('admin','staff') AND employee_id IS NOT NULL AND contractor_id IS NULL)
         OR (role = 'contractor' AND employee_id IS NULL AND contractor_id IS NOT NULL))
);

-- ============================================================================
-- 常用查询索引
-- ============================================================================
CREATE INDEX idx_contract_lines_contract ON contract_lines(contract_id);
CREATE INDEX idx_contract_lines_item ON contract_lines(item_id);
CREATE INDEX idx_contract_changes_contract ON contract_changes(contract_id);
CREATE INDEX idx_contract_changes_group ON contract_changes(change_group_id);
CREATE INDEX idx_repair_orders_contractor ON repair_orders(contractor_id);
CREATE INDEX idx_repair_orders_status ON repair_orders(status);
CREATE INDEX idx_repair_orders_item ON repair_orders(item_id);
CREATE INDEX idx_rental_items_current_store ON rental_items(current_store_id);
CREATE INDEX idx_rental_items_status ON rental_items(status);
CREATE INDEX idx_rental_contracts_status ON rental_contracts(status);
CREATE INDEX idx_rental_contracts_customer ON rental_contracts(customer_id);
CREATE INDEX idx_shifts_work_date ON shifts(work_date);
CREATE INDEX idx_contractor_rates_contractor ON contractor_rates(contractor_id);
CREATE INDEX idx_accounts_uid ON accounts(uid);

-- 客户邮箱 trim 后、大小写不敏感唯一（与 DataService 查重语义一致）
CREATE UNIQUE INDEX uq_customers_email_ci ON customers (lower(btrim(email))) WHERE email IS NOT NULL;

-- 同一设备最多一条「借出中」明细（防止同一设备被两笔合同同时借出）
CREATE UNIQUE INDEX uq_contract_lines_item_active ON contract_lines(item_id) WHERE status = '借出中';

-- ============================================================================
-- 业务序号 sequence（并发安全的全局递增 ID 来源，仅供 SECURITY DEFINER RPC 使用）
--   contract_no_seq：合同编号全局序号（RC+YYYYMMDD+4位序号）
--   change_group_seq：换货变更组号
--   seed 迁移末尾会 setval 到当前最大值，避免与种子显式主键冲突。
-- ============================================================================
CREATE SEQUENCE contract_no_seq;
CREATE SEQUENCE change_group_seq;
